name: moudiki
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:categories/:title
title: Thierry Moudiki's webpage
url: https://thierrymoudiki.github.io
disqus: 
  shortname: tmoudiki
plugins: 
  - jekyll-feed
  - jekyll-jupyter-notebook
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true   # change to false to default to comments off site-wide
