name: moudiki
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
title: Thierry Moudiki's webpage
url: https://thierrymoudiki.github.io
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap